title: Gaurav Gurjar
description: Data Engineer | Building scalable data pipelines, automation, and analytics solutions | Python & SQL focused
url: "https://dataengineergaurav.github.io"
github_username: dataengineergaurav
twitter_username: dubaidataguy
linkedin_username: ggurjarsocl
google_analytics:
theme: jekyll-theme-minimal
# Optional: better SEO
author:
  name: Gaurav Gurjar
  email: ggurjar333@gmail.com
  phone: +971 50 963 6801