title: Gaurav Gurjar
description: Data Engineer | Dubai, UAE
url: ""
baseurl: ""
github_username: dataengineergaurav
google_analytics:
theme: jekyll-theme-minimal
# Optional: better SEO
author:
  name: Gaurav Gurjar